apiVersion: management.loft.sh/v1
kind: NodeProvider
metadata:
  name: auto-nodes-azure
spec:
  terraform:
    nodeEnvironmentTemplate:
      infrastructure:
        git:
          repository: https://github.com/loft-sh/vcluster-auto-nodes-azure.git
          tag: v0.1.0
          subPath: environment/infrastructure
      kubernetes:
        git:
          repository: https://github.com/loft-sh/vcluster-auto-nodes-azure.git
          tag: v0.1.0
          subPath: environment/kubernetes
    nodeTemplate:
      git:
        repository: https://github.com/loft-sh/vcluster-auto-nodes-azure.git
        tag: v0.1.0
        subPath: node
    nodeTypes:
    - name: standard-d2s-v5
      resources:
        cpu: "2"
        memory: 8Gi
      properties:
        instance-type: Standard_D2s_v5
        location: "eastus"
        resource-group: "*"
        subscription-id: "*"
    - name: standard-d4s-v5
      resources:
        cpu: "4"
        memory: 16Gi
      properties:
        instance-type: Standard_D4s_v5
        location: "eastus"
        resource-group: "*"
        subscription-id: "*"
    - name: standard-d8s-v5
      resources:
        cpu: "8"
        memory: 32Gi
      properties:
        instance-type: Standard_D8s_v5
        location: "eastus"
        resource-group: "*"
        subscription-id: "*"
    - name: standard-d16s-v5
      resources:
        cpu: "16"
        memory: 64Gi
      properties:
        instance-type: Standard_D16s_v5
        location: "eastus"
        resource-group: "*"
        subscription-id: "*"
    
